DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
  EMPLOYEEID INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) DEFAULT NULL,
  time VARCHAR(250) DEFAULT NULL,
  duration VARCHAR(250) DEFAULT NULL
);